const LANG_EN_INVITATIONS = {
    CREATE: "Create",
    TEMPLATES: "Templates",
    QUICK_CREATE_PLACEHOLDER: "Add 'Event @ Date'",
    BIRTHDAY_TITLE: "Birthday Party",
    BIRTHDAY_DESC: "Perfect for birthday celebrations with cake and balloons theme",
    WEDDING_TITLE: "Wedding",
    WEDDING_DESC: "Elegant design for wedding invitations and ceremonies",
    MEETING_TITLE: "Business Meeting",
    MEETING_DESC: "Professional template for corporate events and meetings",
    PARTY_TITLE: "General Party",
    PARTY_DESC: "Fun template for any celebration or gathering",
    GRADUATION_TITLE: "Graduation",
    GRADUATION_DESC: "Academic theme for graduation ceremonies",
    CUSTOM_TITLE: "Custom Design",
    CUSTOM_DESC: "Start from scratch with your own design",
    MODERN_MINIMALIST_TITLE: "Modern Minimalist",
    MODERN_MINIMALIST_DESC: "Clean and contemporary design",
    VINTAGE_CLASSIC_TITLE: "Vintage Classic",
    VINTAGE_CLASSIC_DESC: "Traditional style with ornate details",
    FLORAL_GARDEN_TITLE: "Floral Garden",
    FLORAL_GARDEN_DESC: "Beautiful botanical designs",
    GEOMETRIC_PATTERN_TITLE: "Geometric Pattern",
    GEOMETRIC_PATTERN_DESC: "Bold shapes and modern patterns",
    NO_INVITATIONS_TITLE: "No invitations created yet",
    NO_INVITATIONS_DESC: "Create your first invitation to get started",
    CREATE_MODAL_TITLE: "Create New Invitation",
    EVENT_TITLE_LABEL: "Event Title",
    DATE_LABEL: "Date",
    TIME_LABEL: "Time",
    LOCATION_LABEL: "Location",
    DESCRIPTION_LABEL: "Description",
    DESCRIPTION_PLACEHOLDER: "Additional details about your event",
    RSVP_EMAIL_LABEL: "RSVP Email (optional)",
    LIVE_PREVIEW_TITLE: "Live Preview",
    PREVIEW_EVENT_TITLE: "Event Title",
    PREVIEW_DETAILS: "Date & Time • Location",
    PREVIEW_DESCRIPTION: "Event description will appear here",
    CREATE_INVITATION_BTN: "Create Invitation",
    DELETE_CONFIRM: "Are you sure you want to delete this invitation?"
};

const LANG_JP_INVITATIONS = {
    CREATE: "作成",
    TEMPLATES: "テンプレート",
    QUICK_CREATE_PLACEHOLDER: "「イベント @ 日付」を追加",
    BIRTHDAY_TITLE: "誕生日パーティー",
    BIRTHDAY_DESC: "ケーキと風船をテーマにした誕生日のお祝いに最適です",
    WEDDING_TITLE: "結婚式",
    WEDDING_DESC: "結婚式の招待状や式典のためのエレガントなデザイン",
    MEETING_TITLE: "ビジネス会議",
    MEETING_DESC: "企業イベントや会議向けのプロフェッショナルなテンプレート",
    PARTY_TITLE: "一般パーティー",
    PARTY_DESC: "あらゆるお祝いや集まりに使える楽しいテンプレート",
    GRADUATION_TITLE: "卒業式",
    GRADUATION_DESC: "卒業式のためのアカデミックなテーマ",
    CUSTOM_TITLE: "カスタムデザイン",
    CUSTOM_DESC: "独自のデザインでゼロから始めましょう",
    MODERN_MINIMALIST_TITLE: "モダンミニマリスト",
    MODERN_MINIMALIST_DESC: "クリーンで現代的なデザイン",
    VINTAGE_CLASSIC_TITLE: "ヴィンテージクラシック",
    VINTAGE_CLASSIC_DESC: "華やかなディテールを持つ伝統的なスタイル",
    FLORAL_GARDEN_TITLE: "フローラルガーデン",
    FLORAL_GARDEN_DESC: "美しい植物のデザイン",
    GEOMETRIC_PATTERN_TITLE: "幾何学模様",
    GEOMETRIC_PATTERN_DESC: "大胆な形とモダンなパターン",
    NO_INVITATIONS_TITLE: "まだ招待状は作成されていません",
    NO_INVITATIONS_DESC: "最初の招待状を作成して始めましょう",
    CREATE_MODAL_TITLE: "新しい招待状を作成",
    EVENT_TITLE_LABEL: "イベントのタイトル",
    DATE_LABEL: "日付",
    TIME_LABEL: "時間",
    LOCATION_LABEL: "場所",
    DESCRIPTION_LABEL: "説明",
    DESCRIPTION_PLACEHOLDER: "イベントに関する追加の詳細",
    RSVP_EMAIL_LABEL: "出欠確認用メールアドレス（任意）",
    LIVE_PREVIEW_TITLE: "ライブプレビュー",
    PREVIEW_EVENT_TITLE: "イベントのタイトル",
    PREVIEW_DETAILS: "日付と時刻 • 場所",
    PREVIEW_DESCRIPTION: "イベントの説明はここに表示されます",
    CREATE_INVITATION_BTN: "招待状を作成",
    DELETE_CONFIRM: "この招待状を本当に削除しますか？"
};

const LANG_DE_INVITATIONS = {
    CREATE: "Erstellen",
    TEMPLATES: "Vorlagen",
    QUICK_CREATE_PLACEHOLDER: "'Ereignis @ Datum' hinzufügen",
    BIRTHDAY_TITLE: "Geburtstagsfeier",
    BIRTHDAY_DESC: "Perfekt für Geburtstagsfeiern mit Kuchen- und Ballon-Thema",
    WEDDING_TITLE: "Hochzeit",
    WEDDING_DESC: "Elegantes Design für Hochzeitseinladungen und Zeremonien",
    MEETING_TITLE: "Geschäftstreffen",
    MEETING_DESC: "Professionelle Vorlage für Firmenveranstaltungen und Meetings",
    PARTY_TITLE: "Allgemeine Party",
    PARTY_DESC: "Lustige Vorlage für jede Feier oder Zusammenkunft",
    GRADUATION_TITLE: "Abschlussfeier",
    GRADUATION_DESC: "Akademisches Thema für Abschlusszeremonien",
    CUSTOM_TITLE: "Eigenes Design",
    CUSTOM_DESC: "Beginnen Sie mit Ihrem eigenen Design von Grund auf neu",
    MODERN_MINIMALIST_TITLE: "Modern Minimalistisch",
    MODERN_MINIMALIST_DESC: "Sauberes und zeitgemäßes Design",
    VINTAGE_CLASSIC_TITLE: "Vintage Klassisch",
    VINTAGE_CLASSIC_DESC: "Traditioneller Stil mit kunstvollen Details",
    FLORAL_GARDEN_TITLE: "Blumengarten",
    FLORAL_GARDEN_DESC: "Wunderschöne botanische Designs",
    GEOMETRIC_PATTERN_TITLE: "Geometrisches Muster",
    GEOMETRIC_PATTERN_DESC: "Kräftige Formen und moderne Muster",
    NO_INVITATIONS_TITLE: "Noch keine Einladungen erstellt",
    NO_INVITATIONS_DESC: "Erstellen Sie Ihre erste Einladung, um loszulegen",
    CREATE_MODAL_TITLE: "Neue Einladung erstellen",
    EVENT_TITLE_LABEL: "Ereignistitel",
    DATE_LABEL: "Datum",
    TIME_LABEL: "Uhrzeit",
    LOCATION_LABEL: "Ort",
    DESCRIPTION_LABEL: "Beschreibung",
    DESCRIPTION_PLACEHOLDER: "Zusätzliche Details zu Ihrer Veranstaltung",
    RSVP_EMAIL_LABEL: "RSVP E-Mail (optional)",
    LIVE_PREVIEW_TITLE: "Live-Vorschau",
    PREVIEW_EVENT_TITLE: "Ereignistitel",
    PREVIEW_DETAILS: "Datum & Uhrzeit • Ort",
    PREVIEW_DESCRIPTION: "Ereignisbeschreibung wird hier angezeigt",
    CREATE_INVITATION_BTN: "Einladung erstellen",
    DELETE_CONFIRM: "Sind Sie sicher, dass Sie diese Einladung löschen möchten?"
};

const LANG_ES_INVITATIONS = {
    CREATE: "Crear",
    TEMPLATES: "Plantillas",
    QUICK_CREATE_PLACEHOLDER: "Añadir 'Evento @ Fecha'",
    BIRTHDAY_TITLE: "Fiesta de Cumpleaños",
    BIRTHDAY_DESC: "Perfecto para celebraciones de cumpleaños con tema de pastel y globos",
    WEDDING_TITLE: "Boda",
    WEDDING_DESC: "Diseño elegante para invitaciones y ceremonias de boda",
    MEETING_TITLE: "Reunión de Negocios",
    MEETING_DESC: "Plantilla profesional para eventos y reuniones corporativas",
    PARTY_TITLE: "Fiesta General",
    PARTY_DESC: "Plantilla divertida para cualquier celebración o reunión",
    GRADUATION_TITLE: "Graduación",
    GRADUATION_DESC: "Tema académico para ceremonias de graduación",
    CUSTOM_TITLE: "Diseño Personalizado",
    CUSTOM_DESC: "Empieza desde cero con tu propio diseño",
    MODERN_MINIMALIST_TITLE: "Moderno Minimalista",
    MODERN_MINIMALIST_DESC: "Diseño limpio y contemporáneo",
    VINTAGE_CLASSIC_TITLE: "Clásico Vintage",
    VINTAGE_CLASSIC_DESC: "Estilo tradicional con detalles ornamentados",
    FLORAL_GARDEN_TITLE: "Jardín Floral",
    FLORAL_GARDEN_DESC: "Hermosos diseños botánicos",
    GEOMETRIC_PATTERN_TITLE: "Patrón Geométrico",
    GEOMETRIC_PATTERN_DESC: "Formas audaces y patrones modernos",
    NO_INVITATIONS_TITLE: "Aún no se han creado invitaciones",
    NO_INVITATIONS_DESC: "Crea tu primera invitación para empezar",
    CREATE_MODAL_TITLE: "Crear Nueva Invitación",
    EVENT_TITLE_LABEL: "Título del Evento",
    DATE_LABEL: "Fecha",
    TIME_LABEL: "Hora",
    LOCATION_LABEL: "Ubicación",
    DESCRIPTION_LABEL: "Descripción",
    DESCRIPTION_PLACEHOLDER: "Detalles adicionales sobre tu evento",
    RSVP_EMAIL_LABEL: "Email de RSVP (opcional)",
    LIVE_PREVIEW_TITLE: "Vista Previa en Vivo",
    PREVIEW_EVENT_TITLE: "Título del Evento",
    PREVIEW_DETAILS: "Fecha y Hora • Ubicación",
    PREVIEW_DESCRIPTION: "La descripción del evento aparecerá aquí",
    CREATE_INVITATION_BTN: "Crear Invitación",
    DELETE_CONFIRM: "¿Estás seguro de que quieres eliminar esta invitación?"
};

const LANG_KO_INVITATIONS = {
    CREATE: "만들기",
    TEMPLATES: "템플릿",
    QUICK_CREATE_PLACEHOLDER: "'이벤트 @ 날짜' 추가",
    BIRTHDAY_TITLE: "생일 파티",
    BIRTHDAY_DESC: "케이크와 풍선 테마의 생일 축하에 적합합니다",
    WEDDING_TITLE: "결혼식",
    WEDDING_DESC: "결혼식 초대장 및 행사를 위한 우아한 디자인",
    MEETING_TITLE: "비즈니스 미팅",
    MEETING_DESC: "기업 행사 및 회의를 위한 전문적인 템플릿",
    PARTY_TITLE: "일반 파티",
    PARTY_DESC: "모든 축하 또는 모임을 위한 재미있는 템플릿",
    GRADUATION_TITLE: "졸업식",
    GRADUATION_DESC: "졸업식을 위한 학술 테마",
    CUSTOM_TITLE: "사용자 정의 디자인",
    CUSTOM_DESC: "자신만의 디자인으로 처음부터 시작하세요",
    MODERN_MINIMALIST_TITLE: "모던 미니멀리스트",
    MODERN_MINIMALIST_DESC: "깨끗하고 현대적인 디자인",
    VINTAGE_CLASSIC_TITLE: "빈티지 클래식",
    VINTAGE_CLASSIC_DESC: "화려한 디테일의 전통적인 스타일",
    FLORAL_GARDEN_TITLE: "플로럴 가든",
    FLORAL_GARDEN_DESC: "아름다운 식물 디자인",
    GEOMETRIC_PATTERN_TITLE: "기하학적 패턴",
    GEOMETRIC_PATTERN_DESC: "대담한 모양과 현대적인 패턴",
    NO_INVITATIONS_TITLE: "아직 생성된 초대장이 없습니다",
    NO_INVITATIONS_DESC: "첫 초대장을 만들어 시작하세요",
    CREATE_MODAL_TITLE: "새 초대장 만들기",
    EVENT_TITLE_LABEL: "이벤트 제목",
    DATE_LABEL: "날짜",
    TIME_LABEL: "시간",
    LOCATION_LABEL: "장소",
    DESCRIPTION_LABEL: "설명",
    DESCRIPTION_PLACEHOLDER: "이벤트에 대한 추가 정보",
    RSVP_EMAIL_LABEL: "회신 이메일(선택 사항)",
    LIVE_PREVIEW_TITLE: "실시간 미리보기",
    PREVIEW_EVENT_TITLE: "이벤트 제목",
    PREVIEW_DETAILS: "날짜 및 시간 • 장소",
    PREVIEW_DESCRIPTION: "이벤트 설명이 여기에 표시됩니다",
    CREATE_INVITATION_BTN: "초대장 만들기",
    DELETE_CONFIRM: "이 초대장을 삭제하시겠습니까?"
};

const LANG_ZH_INVITATIONS = {
    CREATE: "创建",
    TEMPLATES: "模板",
    QUICK_CREATE_PLACEHOLDER: "添加“活动 @ 日期”",
    BIRTHDAY_TITLE: "生日派对",
    BIRTHDAY_DESC: "适合以蛋糕和气球为主题的生日庆祝活动",
    WEDDING_TITLE: "婚礼",
    WEDDING_DESC: "适用于婚礼请柬和仪式的优雅设计",
    MEETING_TITLE: "商务会议",
    MEETING_DESC: "适用于公司活动和会议的专业模板",
    PARTY_TITLE: "普通派对",
    PARTY_DESC: "适用于任何庆祝或聚会的有趣模板",
    GRADUATION_TITLE: "毕业典礼",
    GRADUATION_DESC: "适用于毕业典礼的学术主题",
    CUSTOM_TITLE: "自定义设计",
    CUSTOM_DESC: "从头开始，使用您自己的设计",
    MODERN_MINIMALIST_TITLE: "现代简约",
    MODERN_MINIMALIST_DESC: "简洁现代的设计",
    VINTAGE_CLASSIC_TITLE: "复古经典",
    VINTAGE_CLASSIC_DESC: "带有华丽细节的传统风格",
    FLORAL_GARDEN_TITLE: "花园花卉",
    FLORAL_GARDEN_DESC: "美丽的植物设计",
    GEOMETRIC_PATTERN_TITLE: "几何图案",
    GEOMETRIC_PATTERN_DESC: "大胆的形状和现代的图案",
    NO_INVITATIONS_TITLE: "尚未创建任何邀请",
    NO_INVITATIONS_DESC: "创建您的第一个邀请以开始",
    CREATE_MODAL_TITLE: "创建新邀请",
    EVENT_TITLE_LABEL: "活动标题",
    DATE_LABEL: "日期",
    TIME_LABEL: "时间",
    LOCATION_LABEL: "地点",
    DESCRIPTION_LABEL: "描述",
    DESCRIPTION_PLACEHOLDER: "关于您活动的更多细节",
    RSVP_EMAIL_LABEL: "回复邮箱（可选）",
    LIVE_PREVIEW_TITLE: "实时预览",
    PREVIEW_EVENT_TITLE: "活动标题",
    PREVIEW_DETAILS: "日期和时间 • 地点",
    PREVIEW_DESCRIPTION: "活动描述将显示在此处",
    CREATE_INVITATION_BTN: "创建邀请",
    DELETE_CONFIRM: "您确定要删除此邀请吗？"
};
